#!/bin/bash

# This script is a configurable alias for "scripts/manage.sh"

###########################################################
# Configuration section
# ---------------------------------------------------------
# Use this section to configure the directories to use when
# running the utility scripts.
# Make a copy of the script and place it where it is
# conveniently available. Change 'SCRIPTS' to point to the
# folder containing the utility script `manage.sh`.
###########################################################
SCRIPTS="./scripts"
PRESENTATIONS_PATH="./presentations"
DIAGRAMS_PATH="./diagrams"
VMDIR="./vms"
PRESENTATIONS_COMMON_STYLE="src/meerkatsstyle.tex"
###########################################################
# End configuration section
###########################################################

MANAGE_SCRIPT="${SCRIPTS}/manage.sh"
source "${MANAGE_SCRIPT}"

manage "$@"
