#!/bin/bash

# This script is an alias for "scripts/manage.sh"

MANAGE_SCRIPT="scripts/manage.sh"
source "${MANAGE_SCRIPT}"

TC="\e[0;31m"
SC="\e[0;32m"
NC="\e[0m"
_info "${TC}Notice${NC}: This is a wrapper script for ${SC}'${MANAGE_SCRIPT}'${NC}. Use \
${SC}'source ${MANAGE_SCRIPT}'${NC} in order to get a real 'manage' command \
with auto completions.
"

manage "$@"
